apartments/urls.py
from django.urls import path

from .views import ApartmentDetailView, ApartmentListView

app_name = "apartments"
urlpatterns = [
    path('', ApartmentListView.as_view(), name="list-apartments"),
    path('<slug:slug>/', ApartmentDetailView.as_view(), name="apartment-detail"),
]

urls.py
# -*- coding: utf-8 -*-
import aldryn_addons.urls
from aldryn_django.utils import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = (
    [
        # add your own patterns here
        path("", include("pages.urls", namespace="pages")),
        path("apartments/", include("apartments.urls", namespace="apartments")),
        path("contact/", include("contact.urls", namespace="contact")),
    ]
    + aldryn_addons.urls.patterns()
    + i18n_patterns(
        # add your own i18n patterns here
        *aldryn_addons.urls.i18n_patterns()  # MUST be the last entry!
    )
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    from django.urls import include, path
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

apartments/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django_extensions.db.fields import AutoSlugField
from django.utils.html import mark_safe
from django.urls import reverse
from pathlib import Path


class ApartmentImage(models.Model):
    image = models.ImageField(upload_to="apartment/image/",
                              null=False,
                              blank=False)
    apartment = models.ForeignKey("apartments.Apartment",
                                  on_delete=models.CASCADE,
                                  blank=False,
                                  null=False,
                                  related_name="images")

    def __str__(self):
        return f"{self.image}"


class Apartment(models.Model):

    class MajorCity(models.TextChoices):
        ACCRA = 'AC', _("Accra")
        KUMASI = 'KU', _("Kumasi")
        KOFORIDUA = 'KO', _("Koforidua")
        SUNYANI = 'SU', _("Sunyani")
        TAMALE = 'TA', _("Tamale")
        KASOA = 'KA', _("Kasoa")
        CAPE_COAST = 'CC', _("Cape Coast")
        TEMA = 'TM', _("Tema")

    class Number(models.IntegerChoices):
        ONE = 1, _('1+')
        TWO = 2, _('2+')
        THREE = 3, _('3+')
        FOUR = 4, _('4+')
        FIVE = 5, _('5+')
        SIX = 6, _('6+')
        SEVEN = 7, _('7+')
        EIGHT = 8, _('8+')
        NINE = 9, _('9+')
        TEN = 10, _('10+')

    agent = models.ForeignKey(
        "agents.Agent",
        verbose_name=_("Agent"),
        help_text="Which agent is in charge of this apartment?",
        related_name="apartments",
        on_delete=models.CASCADE,
        null=True,
        blank=False)
    upload_time = models.DateTimeField(verbose_name=_("Date Uploaded"),
                                       auto_now_add=True)
    title = models.CharField(
        verbose_name=("Title"),
        help_text="Example: 3 bedroom apartment at Kumasi, Ghana.",
        max_length=250,
        default="",
        blank=False,
        null=False)
    slug = AutoSlugField(populate_from="title")
    for_sale = models.BooleanField(verbose_name=_("For Sale"),
                                   help_text="Is this apartment for sale?",
                                   default=False)
    for_rent = models.BooleanField(verbose_name=_("For Rent"),
                                   help_text="Is this apartment for rent?",
                                   default=True)
    available = models.BooleanField(
        verbose_name=("Available"),
        help_text="Check this box if the apartment has NOT been rented out.",
        default=True)
    featured = models.BooleanField(
        verbose_name=_("Featured Listing"),
        help_text="If this apartment is featured, it is going to be displayed on the homepage and also will be at the top of apartment listings",
        default=False)
    hall = models.BooleanField(
        verbose_name=_("Hall"),
        help_text="Does this apartment have a hall? Tick if yes.",
        default=False)
    self_contained = models.BooleanField(
        verbose_name=_("Self Contained"),
        help_text="Is this apartment self contained? Tick if yes.",
        default=True)
    verified = models.BooleanField(
        verbose_name=_("Verified"),
        help_text="Has this apartment been verified? Tick if Yes",
        default=False)
    major_city = models.CharField(
        verbose_name=_("Major City"),
        help_text="Please select the major city that your apartment is located in.",
        max_length=20,
        choices=MajorCity.choices,
        default=MajorCity.KUMASI)
    location = models.CharField(verbose_name=_("Location"),
                                help_text="Where is this apartment located?",
                                max_length=50,
                                null=False,
                                blank=False,
                                default="")
    bedrooms = models.PositiveSmallIntegerField(
        verbose_name=_("Number of Bedrooms"),
        help_text="What is the total number of bedrooms in this apartment?",
        default=1)
    baths = models.PositiveSmallIntegerField(
        verbose_name=_("Number of Baths"),
        help_text="How many baths are in this apartment?",
        default=1)

    advance_years = models.PositiveSmallIntegerField(
        verbose_name=_("Years of Advance Payment"),
        help_text="If this place is being rented out, how many years of advance payment is required?",
        default=1)
    monthly_rent_payment = models.FloatField(
        verbose_name=_("Monthly Rent Payment"),
        help_text="How much is a tenant going to pay for the place every month?",
        blank=False,
        null=False)
    description = models.TextField(
        verbose_name=_("Extra Description"),
        help_text="Enter any extra details the potential occupant needs to know",
        blank=True,
        null=True)
    total_rent_payment = models.FloatField(
        verbose_name=_("Total Rent Payment"),
        help_text="Amount tenant will pay over years of residency, monthly_payment * advance_years"
    )
    agent_commission = models.PositiveSmallIntegerField(
        verbose_name=_("Agent's Commission ( percentage )"),
        help_text="What is the commission the agent will take, in percentage.",
        default=5)
    agent_fee = models.FloatField(verbose_name="Agent's Fee ( amount )",
                                  help_text="Amount to pay to the agent.",
                                  blank=True,
                                  null=True)
    inspection_fee = models.PositiveSmallIntegerField(
        verbose_name=_("Inspection Fee"),
        help_text="How much is this agent charging potential clients to go show them the place?",
        default=50)

    def get_absolute_url(self):
        return reverse("apartments:apartment-detail",
                       kwargs={"slug": self.slug})

    def images_count(self):
        return self.images.count()

    def get_monthly_rent_payment(self):
        return "{:.2f}".format(self.monthly_rent_payment)

    def get_total_rent_payment(self):
        return "{:.2f}".format(self.total_rent_payment)

    def get_agent_fee(self):
        return "{:.2f}".format(self.agent_fee)

    def get_inspection_fee(self):
        return "{:.2f}".format(self.inspection_fee)

    def get_number_of_advance_months(self):
        return self.advance_years * 12

    def __str__(self):
        return f"{self.title}"

    def image_tag(self):
        if self.images:
            url = self.images.first().image.url
            parts = url.split(".jpg")
            jpeg_thumbnail = parts[0] + ".thumbnail.jpg"
            webp_thumbnail = parts[0] + ".thumbnail.webp"
            return mark_safe(
                f'<img src="{jpeg_thumbnail}" style="width: 200px; height:200px;" />'
            )
        else:
            return 'No Image Found'

    image_tag.short_description = "Apartment's Image"

    def save(self, *args, **kwargs):
        _total_rent_amount = self.monthly_rent_payment * self.advance_years * 12

        self.agent_fee = self.agent_commission * 0.01 * _total_rent_amount
        self.total_rent_payment = _total_rent_amount

        return super(Apartment, self).save(*args, **kwargs)

    class Meta:
        ordering = ("-upload_time", )
        verbose_name = "Apartment"
        verbose_name_plural = "Apartments"

        indexes = [
            models.Index(fields=['-upload_time'], name="ordering_idx"),
            models.Index(fields=['featured', 'verified', 'major_city', 'location',
                         'bedrooms', 'baths', 'advance_years', 'monthly_rent_payment'], name="filter_idx")
        ]

apartments/views.py
from contact.forms import InquiryForm, ScheduleMeetingForm
from django.views.generic import DetailView, ListView
from django_filters.views import FilterView

from apartments.filters import ApartmentFilter
from apartments.models import Apartment


class ApartmentListView(FilterView):
    queryset = (
        Apartment.objects.all().select_related("agent").prefetch_related("images")
    )
    filterset_class = ApartmentFilter
    paginate_by = 8
    context_object_name = "apartments"


class ApartmentDetailView(DetailView):
    queryset = (
        Apartment.objects.all().select_related("agent").prefetch_related("images")
    )
    context_object_name = "apartment"
    template_name = "apartments/detail-apartment.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ask_question_form"] = InquiryForm()
        context["schedule_meeting_form"] = ScheduleMeetingForm()
        return context

templates/apartments/apartment-card.html
{% load static humanize apartments_extras %}

<div class="listing-container">
  {% for apartment in apartments %}
  <a href="{{ apartment.get_absolute_url }}" data-aos="zoom-in" data-aos-duration="200">
    <div class="apartment-card">
      <!-- The apartment image -->

      {% get_thumbnail_images apartment as thumbnails %}
      <picture class="relative h-64">
        <source class="w-full h-64" srcset="{{ thumbnails.webp }}" type="image/webp">
        <source class="w-full h-64" srcset="{{ thumbnails.jpeg }}" type="image/jpeg">
        <img class="w-full h-64" src="{{ thumbnails.jpeg }}" alt="Apartment Image" />
        <div class="absolute top-5 left-4 flex space-x-2 text-slate-200 bg-slate-900 bg-opacity-60 font-bold p-2 rounded-lg">      
          <span class="self-center">{{ apartment.images.count }}</span>
          <i class="self-center fa-solid fa-camera text-xl text-white"></i>
        </div>
      </picture>

      <!-- The apartment info -->
      <div class="px-2 py-3">
        <!-- TODO add the title of the post under the image -->
        <p class="text-sm text-slate-200"><i class="fa-solid fa-clock"></i> {{ apartment.upload_time|naturaltime }}</p>

        <!-- location -->
        <address class="py-2 text-slate-100 font-semibold">
          <i class="fa-solid fa-map-marker-alt text-cyan-200 mr-2"></i>{{apartment.location}}, {{ apartment.get_major_city_display }}
        </address>

        <!-- Price, monthly -->
        <p class="text-lg font-serif font-black  py-5">
          <i class="fa-solid fa-money-bill-wave text-emerald-200"></i>
          <span class="mr-1 text-emerald-200">Ghc</span><span class="text-white">{{ apartment.get_monthly_rent_payment|intcomma }}</span><span
            class="ml-2 text-white">monthly</span>
          <span class="-pt-1 text-sm text-sky-100 text-semi-bold block">
            {{ apartment.advance_years }} year{{ apartment.advance_years|pluralize }} advance payment
          </span>
        </p>
        

        <!-- Baths, beds and verified -->
        <div class="flex justify-between py-1">
          <div class="self-center text-gray-100">
            <span class="font-bold text-lg">{{ apartment.bedrooms }}</span>
            <span class="text-slate-100">bed{{ apartment.bedrooms|pluralize }}</span>
            <i class="fa-solid fa-bed text-sky-500"></i>
          </div>
          <div class="self-center text-white">
            <span class="font-bold text-lg">{{ apartment.baths }}</span>
            <span class="text-white">bath{{ apartment.baths|pluralize }}
            </span>
            <i class="fa-solid fa-bath text-sky-500"></i>
          </div>
          <div class="self-center text-white">
            verified {% if apartment.verified %}
            <i class="fa-solid fa-check-double text-green-300"></i>
            {% else %}
            <i class="fa-solid fa-times text-red-300"></i>
            {% endif %}
          </div>
        </div>

        <!-- Agent -->
        <p class="text-white py-1">
          <span class="font-bold">Agent</span>
          <i class="fa-solid fa-user-tie text-white"></i>:
          {{apartment.agent.full_name}}
        </p>
      </div>
    </div>
  </a>
  {% empty %}
  <h1 class="text-red-600 text-lg">There are no apartments</h1>
  {% endfor %}
</div>

templates/apartments/apartment-listings.html
{% load static humanize apartments_extras %}

<div class="listing-container">
  {% for apartment in apartments %}
  <a href="{{ apartment.get_absolute_url }}" data-aos="zoom-in" data-aos-duration="200">
    <div class="apartment-card">
      <!-- The apartment image -->

      {% get_thumbnail_images apartment as thumbnails %}
      <picture class="relative h-64">
        <source class="w-full h-64" srcset="{{ thumbnails.webp }}" type="image/jpeg">
        <source class="w-full h-64" srcset="{{ thumbnails.jpeg }}" type="image/jpeg">
        <img class="w-full h-64" src="{{ thumbnails.jpeg }}" alt="Apartment Image" />
        <div class="absolute top-5 left-4 flex space-x-2 text-slate-200 font-bold">      
          <span>{{ apartment.images.count }}</span>
          <i class="fa-solid fa-camera text-black-rich text-xl"></i>
        </div>
      </picture>

      <!-- The apartment info -->
      <div class="px-2 py-3">
        <!-- TODO add the title of the post under the image -->
        <p class="text-sm text-slate-200"><i class="fa-solid fa-clock"></i> {{ apartment.upload_time|naturaltime }}</p>

        <!-- location -->
        <address class="py-2 text-slate-100 font-semibold">
          <i class="fa-solid fa-map-marker-alt text-cyan-200 mr-2"></i>{{apartment.location}}, {{ apartment.get_major_city_display }}
        </address>

        <!-- Price, monthly -->
        <p class="text-lg font-serif font-black  py-5">
          <i class="fa-solid fa-money-bill-wave text-emerald-200"></i>
          <span class="mr-1 text-emerald-200">Ghc</span><span class="text-white">{{ apartment.get_monthly_rent_payment|intcomma }}</span><span
            class="ml-2 text-white">monthly</span>
          <span class="-pt-1 text-sm text-sky-100 text-semi-bold block">
            {{ apartment.advance_years }} year{{ apartment.advance_years|pluralize }} advance payment
          </span>
        </p>
        

        <!-- Baths, beds and verified -->
        <div class="flex justify-between py-1">
          <div class="self-center text-gray-100">
            <span class="font-bold text-lg">{{ apartment.bedrooms }}</span>
            <span class="text-slate-100">bed{{ apartment.bedrooms|pluralize }}</span>
            <i class="fa-solid fa-bed text-sky-500"></i>
          </div>
          <div class="self-center text-white">
            <span class="font-bold text-lg">{{ apartment.baths }}</span>
            <span class="text-white">bath{{ apartment.baths|pluralize }}
            </span>
            <i class="fa-solid fa-bath text-sky-500"></i>
          </div>
          <div class="self-center text-white">
            verified {% if apartment.verified %}
            <i class="fa-solid fa-check-double text-green-300"></i>
            {% else %}
            <i class="fa-solid fa-times text-red-300"></i>
            {% endif %}
          </div>
        </div>

        <!-- Agent -->
        <p class="text-white py-1">
          <span class="font-bold">Agent</span>
          <i class="fa-solid fa-user-tie text-white"></i>:
          {{apartment.agent.full_name}}
        </p>
      </div>
    </div>
  </a>
  {% empty %}
  <h1 class="text-red-600 text-lg">There are no apartments</h1>
  {% endfor %}
</div>

templates/apartments/detail-apartment.html
{% extends 'base.html' %}
{% load static humanize %}

{% block extra_css %}
{% comment %} <link rel="stylesheet" href="{%static 'css/custom/slide-show.css' %}"> {% endcomment %}
{% endblock extra_css %}

{% block title %}{{ apartment.title }}{% endblock title %}


{% block content %}


<div class="fixed w-full top-0 z-50 hidden" id="ask-question-popup">
  {% include 'contact/ask-question-form.html' with apartment=apartment %}
</div>

<div class="fixed w-full top-0 z-50 hidden" id="schedule-meeting-popup">
  {% include 'contact/schedule-meeting-form.html' with apartment=apartment %}
</div>

<div class="mb-20 xl:px-40">
  <div class="py-3 px-2 md:px-10">
    <!-- Title -->
    <div class="">
      <p class="text-slate-900 text-center md:text-left text-lg font-bold">{{ apartment.title }}</p>
      <p class="text-sm text-center md:text-left py-1 text-slate-800 md:hidden">Posted: <i class="fa-solid fa-clock"></i>
        {{apartment.upload_time|naturaltime }}</p>
    </div>

    <!-- Location, Price Info -->
    <div class="hidden md:flex justify-between space-x-10 py-2">
      <div class="self-center flex">
        <i class="self-center fa-solid fa-map-marker-alt text-cyan-500 mr-2 text-xl"></i>
        <address class="self-center text-gray-900 font-bold">
          {{ apartment.get_major_city_display }}, {{ apartment.location }}
        </address>
      </div>

      <div class="text-right text-slate-800 self-center flex md:hidden">
        <!-- Add tooltips so people can click and know what each amount is for -->
        <p class="flex">
          <span class="self-center mr-1 text-sm text-slate-800">Total Rent:</span> 
          <span class="self-center font-semibold">Ghc {{ apartment.get_total_rent_payment|intcomma }}</span>
        </p>
      </div>

      <div class="flex">
        <p class="flex">
          <span class="self-center mr-1 text-sm text-slate-800">Monthly Rent:</span>
          <span class="self-center font-semibold lg:text-2xl font-sans">Ghc {{ apartment.get_monthly_rent_payment|intcomma }}</span>
        </p>
      </div>

      <div>
        <p class="flex">
          <button
            class="px-2 w-full text-center py-1 rounded-md bg-blue-700 hover:bg-blue-600 text-white font-bold schedule-meeting-btn">
            Schedule Meeting
          </button>
        </p>
      </div>
    </div>

    <!-- Baths, Beds and Verified -->
    <div class="hidden md:flex space-x-10 text-base">
      <div class="text-center flex space-x-2">
        <p class="self-center apt__info-label-2">Beds:</p>
        <p class="self-center apt__info-text-1">{{ apartment.bedrooms }}</p>
      </div>

      <div class="text-center flex space-x-2">
        <p class="self-center apt__info-label-2">Baths:</p>
        <p class="self-center apt__info-text-1">{{ apartment.baths }}</p>
      </div>

      <div class="text-center flex space-x-2">
        <p class="self-center apt__info-label-2">Verified:</p>
        <p class="self-center">
          {% if apartment.verified %}
          <i class="fa-solid fa-check-double text-green-600 text-xl"></i>
          {% else %}
          <i class="fa-solid fa-times text-red-600 text-xl"></i>
          {% endif %}
        </p>
      </div>

      <div class="flex space-x-2">
        <p class="self-center apt__info-label-2">Posted:</p>
        <p class="self-center"><i class="fa-solid fa-clock"></i> {{apartment.upload_time|naturaltime }}</p>
      </div>
    </div>
  </div>

  <!-- Create a carousel of the images, on click, user can view the full image -->
  {% comment %} <div class="w-full h-72 md:h-96">
    <img class="h-72 md:h-96 w-full" src="{{ apartment.images.first.image.url }}" alt="{{ apartment.title }} Image">
  </div> {% endcomment %}
  <div class="slide-container">
    {% for apartment_image in apartment.images.all %}
    <div class="slide">
      <img 
          class="slide-img" 
          src="{{ apartment_image.image.url }}" alt=""
        >
    </div>
    {% endfor %}

    <div class="button absolute top-1/2 left-0 flex w-full justify-between z-10">
      <a 
        class="prev prev-next-btn" 
        onclick="nextImg(-1)" 
        >&#10094;</a>
      <a 
        class="next prev-next-btn" 
        onclick="nextImg(1)"
        >&#10095;</a>
    </div>

    <div class="dots flex flex-wrap space-x-2 text-center absolute top-0 bg-black-rich bg-opacity-80 px-2 py-3 h-8">
      {% for apartment_image in apartment.images.all %}
        <div class="dot" onclick="currentSlide({{ forloop.counter }})"></div>
      {% endfor %}
    </div>
  </div>

  <div class="md:px-10">
    <!-- Location, Price Info -->
    <div class="apt__info-box md:hidden">
      <div class="w-1/2 self-center flex">
        <i class="self-center fa-solid fa-map-marker-alt text-cyan-500 mr-2 text-xl"></i>
        <address class="self-center text-gray-900 font-bold">
          {{ apartment.get_major_city_display }}, {{ apartment.location }}
        </address>
      </div>

      <div class="w-1/2 text-right text-slate-800 font-bold text-lg self-center">
        <!-- Add tooltips so people can click and know what each amount is for -->
        <p><span class="text-sm text-slate-700">Total Rent:</span> <br />Ghc {{ apartment.get_total_rent_payment|intcomma }}</p>
        <p><span class="text-sm text-slate-700">Monthly Rent:</span> <br/> Ghc {{ apartment.get_monthly_rent_payment|intcomma }}</p>
      </div>
    </div>

    <!-- Baths, Beds and Verified -->
    <div class="apt__info-box justify-between md:hidden lg">
      <div class="text-center">
        <p class="apt__info-label-1">Beds <i class="fa-solid fa-bed text-sky-600"></i></p>
        <p class="apt__info-text-1">{{ apartment.bedrooms }}</p>
      </div>

      <div class="text-center">
        <p class="apt__info-label-1">Baths <i class="fa-solid fa-bath text-sky-600"></i></p>
        <p class="apt__info-text-1">{{ apartment.baths }}</p>
      </div>

      <div class="text-center">
        <p class="apt__info-label-1">Verified</p>
        <p>
          {% if apartment.verified %}
          <i class="fa-solid fa-check-double text-green-600 text-xl"></i>
          {% else %}
          <i class="fa-solid fa-times text-red-600 text-xl"></i>
          {% endif %}
        </p>
      </div>
    </div>

    <!-- CTA -->
    <div class="apt__info-box">
      <div class="w-1/2 lg:w-1/3 self-center text-xl font-black">
        <div class="flex flex-col">
          <span class="text-blue-700">Isotach</span>
          <span class="text-blue-900">Global</span>
        </div>
      </div>
      <div class="lg:self-center flex flex-col lg:flex-row w-1/2 lg:w-2/3 space-y-2 lg:space-y-0 lg:space-x-5">
        <button
          class="px-2 w-full  lg:self-center text-center py-2 rounded-md bg-blue-700 hover:bg-blue-600 text-white font-bold schedule-meeting-btn">Schedule
          Meeting</button>

        <button
          class="px-2 w-full lg:self-center  text-center py-2 rounded-md bg-slate-900 hover:bg-slate-800 text-white font-bold ask-question-btn">Ask a
          Question</button>
      </div>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3">
      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Availability:</span>
          {% if apartment.available %}
          <span class="apt__info-yes">available</span>
          {% else %}
          <span class="apt__info-no">not available</span>
          {% endif %}
        </p>
      </div>

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Featured Listing:</span>
          {% if apartment.featured %}
          <span class="apt__info-yes">yes</span>
          {% else %}
          <span class="apt__info-no">no</span>
          {% endif %}
        </p>
      </div>

      {% if apartment.for_rent %}
        <div class="apt__info-box">
          <p>
            <span class="apt__info-label-2">For Rent:</span>
            <span class="apt__info-yes">yes</span>
          </p>
        </div>
      {% endif %}

      {% if apartment.for_sale %}
        <div class="apt__info-box">
          <p>
            <span class="apt__info-label-2">For Sale:</span>
            <span class="apt__info-yes">yes</span>
          </p>
        </div>
      {% endif %}

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Hall:</span>
          {% if apartment.hall %}
          <span class="apt__info-yes">yes</span>
          {% else %}
          <span class="apt__info-no">no</span>
          {% endif %}
        </p>
      </div>

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Self Contained:</span>
          {% if apartment.self_contained %}
          <span class="apt__info-yes">yes</span>
          {% else %}
          <span class="apt__info-no">no</span>
          {% endif %}
        </p>
      </div>

      {% if apartment.for_rent %}

        <div class="apt__info-box">
          <p>
            <span class="apt__info-label-2">Years in Advance Payment:</span>
            <span class="apt__info-text-2">{{ apartment.advance_years }}</span>
          </p>
        </div>

        <div class="apt__info-box">
          <p>
            <span class="apt__info-label-2">Months in Advance Payment:</span><br class="hidden xl:block 2xl:hidden"/>
            <span class="apt__info-text-2">{{ apartment.get_number_of_advance_months }}</span>
          </p>
        </div>

        <div class="apt__info-box">
          <p>
            <span class="apt__info-label-2">Monthly Rent Payment:</span><br class="hidden xl:block 2xl:hidden"/>
            <span class="apt__info-text-2">Ghc {{ apartment.get_monthly_rent_payment|intcomma }}</span>
          </p>
        </div>

        <div class="apt__info-box">
          <p>
            <span class="apt__info-label-2">Total Rent Payment:</span><br class="hidden xl:block 2xl:hidden"/>
            <span class="apt__info-text-2">Ghc {{ apartment.get_total_rent_payment|intcomma }}</span>
          </p>
        </div>

        <div class="apt__info-box md:col-span-2 lg:col-span-3">
          <p>
            <span class="apt__info-label-2">Extra Description:</span><br /><br />
            <span class="text-base text-slate-900 text-justify">{{ apartment.description }}</span>
          </p>
        </div>

      {% endif %}
    
    </div>

    <!-- Agent's Details -->
    <div class="my-10 md:my-16">
      <h1 class="text-center lg:text-left text-black-rich uppercase text-xl py-3 font-bold">Agent's Info</h1>

      <div class="border-t border-t-gray-500 apt__info-box">
        <p>
          <span class="apt__info-label-2">Name:</span>
          <span class="apt__info-text-2">{{ apartment.agent.full_name }}</span>
        </p>
      </div>

      <div class="apt__info-box">
        <p class="flex space-x-8">
          <span class="apt__info-label-2 self-center">Photo:</span>
          <span class="">
            <img class="" src="{{ apartment.agent.picture.url }}"
              style="width: 250px; height:250px;" alt="{{ apartment.agent.full_name }}'s Picture" />
          </span>
        </p>
      </div>

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Phone:</span>
          <span class="apt__info-text-2">{{ apartment.agent.phone_number }}</span>
        </p>
      </div>

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Email:</span>
          <span class="apt__info-text-2">{{ apartment.agent.email }}</span>
        </p>
      </div>

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Verified:</span>
          {% if apartment.agent.verified %}
          <span class="apt__info-yes">yes</span>
          {% else %}
          <span class="apt__info-no">no</span>
          {% endif %}
        </p>
      </div>

    </div>

    <!-- Fees and Commissions -->
    <div class="my-10 md:my-16">
      <h1 class="text-center lg:text-left text-black-rich uppercase text-xl py-3 font-bold">Fees and Commissions</h1>

      <div class="border-t border-t-slate-300 apt__info-box">
        <p>
          <span class="apt__info-label-2">Inspection Fee:</span>
          <span class="apt__info-text-2">Ghc {{ apartment.get_inspection_fee|intcomma }}</span>
        </p>
      </div>

      <div class="apt__info-box">
        <p>
          <span class="apt__info-label-2">Agent's Commission / Fee:</span>
          <span class="apt__info-text-2">Ghc {{ apartment.get_agent_fee|intcomma }}</span>
        </p>
      </div>
    </div>

  </div>

  <!-- TODO other similar listings -->
</div>


{% endblock content %}


{% block javascript %}
<script src="{% static 'js/custom/apartments-detail.js' %}"></script>
{% endblock javascript %}