apartments/urls.py
from django.urls import path

from .views import ApartmentDetailView, ApartmentListView

app_name = "apartments"
urlpatterns = [
    path('', ApartmentListView.as_view(), name="list-apartments"),
    path('<slug:slug>/', ApartmentDetailView.as_view(), name="apartment-detail"),
]

contact/urls.py
from django.urls import path
from .views import (
    HandleContactFormView,
    ContactFormSuccessView,
    HandleNewsletterSignupFormView,
    NewsletterSignupFormSuccessView,
    HandleInquiryFormView,
    InquiryFormSuccessView,
    HandleScheduleMeetingFormView,
    ScheduleMeetingSuccessView,
)

app_name = "contact"
urlpatterns = [
    # contact form urls
    path("contact-us/", HandleContactFormView.as_view(), name="handle-contact"),
    path(
        "contact-us/success/", ContactFormSuccessView.as_view(), name="contact-success"
    ),
    # newsletter signup urls
    path(
        "newsletter-signup/",
        HandleNewsletterSignupFormView.as_view(),
        name="handle-newsletter",
    ),
    path(
        "newsletter-signup/success/",
        NewsletterSignupFormSuccessView.as_view(),
        name="newsletter-success",
    ),
    # inquiry
    path("ask-question/", HandleInquiryFormView.as_view(), name="handle-inquiry"),
    path(
        "ask-question/success/",
        InquiryFormSuccessView.as_view(),
        name="inquiry-success",
    ),
    # schedule meeting
    path(
        "schedule-meeting/",
        HandleScheduleMeetingFormView.as_view(),
        name="schedule-meeting",
    ),
    path(
        "schedule-meeting/success/",
        ScheduleMeetingSuccessView.as_view(),
        name="schedule-meeting-success",
    ),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

app_name="pages"
urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
]

urls.py
# -*- coding: utf-8 -*-
import aldryn_addons.urls
from aldryn_django.utils import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = (
    [
        # add your own patterns here
        path("", include("pages.urls", namespace="pages")),
        path("apartments/", include("apartments.urls", namespace="apartments")),
        path("contact/", include("contact.urls", namespace="contact")),
    ]
    + aldryn_addons.urls.patterns()
    + i18n_patterns(
        # add your own i18n patterns here
        *aldryn_addons.urls.i18n_patterns()  # MUST be the last entry!
    )
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    from django.urls import include, path
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

contact/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from django.utils.translation import gettext_lazy as _
from apartments.models import Apartment


class BasicContactInformation(models.Model):
    full_name = models.CharField(
        verbose_name=_("Full Name"),
        max_length=50,
        null=False,
        blank=False,
    )
    phone_number = PhoneNumberField(blank=True, null=True)
    email = models.EmailField(
        verbose_name=_("Email Address"),
        max_length=300,
        blank=False,
        null=False,
    )

    class Meta:
        abstract = True


class Contact(BasicContactInformation):
    city = models.CharField(
        verbose_name=_("City / Town"),
        max_length=100,
        null=False,
        blank=False,
    )
    message = models.TextField(verbose_name=_("Message"), max_length=1000)
    date_and_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Contact Message"
        verbose_name_plural = "Contact Messages"


class Newsletter(BasicContactInformation):
    signup_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Newsletter Signup"
        verbose_name_plural = "Newsletter Signups"


class ApartmentDetailViewFormBasicContactInformation(BasicContactInformation):
    submitted = models.DateTimeField(
        verbose_name=_("Form Submission Date and Time"), auto_now_add=True
    )
    apartment_link = models.URLField(
        verbose_name=_("Link to Apartment"), blank=False, null=False, default=""
    )
    apartment_title = models.CharField(
        verbose_name=_("Apartment Title"),
        null=False,
        blank=False,
        default="",
        max_length=200,
    )
    agent_name = models.CharField(
        verbose_name=_("Agent's Name"),
        null=False,
        blank=False,
        default="",
        max_length=50,
    )

    class Meta:
        abstract = True


class Inquiry(ApartmentDetailViewFormBasicContactInformation):
    question = models.TextField(blank=False, null=False)

    def __str__(self):
        return f"{self.full_name} - Inquiry"

    class Meta:
        verbose_name = "Inquiry"
        verbose_name_plural = "Inquiries"


class ScheduleMeeting(ApartmentDetailViewFormBasicContactInformation):
    meeting_date_and_time = models.DateTimeField(null=False, blank=False)

    def __str__(self):
        return f"{self.full_name} - Scheduled Meeting"

    class Meta:
        ordering = ("-submitted",)
        verbose_name = "Scheduled Meeting"
        verbose_name_plural = "Scheduled Meetings"


class SiteAdministrator(models.Model):
    """Model to add site admins to the website from the admin interface"""

    full_name = models.CharField(
        verbose_name=_("Full Name"), max_length=50, null=True, blank=True
    )
    email = models.EmailField(
        _("Email Address"), max_length=254, blank=False, null=False
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name = "Site Administrator"
        verbose_name_plural = "Site Administrators"
        ordering = ["created"]

contact/forms.py
from django import forms
from django.conf import settings
from django.template.loader import render_to_string

from .models import Contact, Inquiry, Newsletter, ScheduleMeeting

from utils.email_utils import send_admin_email, send_site_visitor_email


class ContactForm(forms.ModelForm):
    def send_email_to_admins(self):
        context = {
            "full_name": self.cleaned_data.get("full_name"),
            "phone_number": self.cleaned_data.get("phone_number"),
            "email": self.cleaned_data.get("email"),
            "city": self.cleaned_data.get("city"),
            "message": self.cleaned_data.get("message"),
        }

        email_subject = "CONTACT MESSAGE FROM WEBSITE VISITOR"
        email_body = render_to_string("emails/contact-email-body_admins.txt", context)

        send_admin_email(email_subject, email_body)

    def send_email_to_site_visitor(self):
        context = {
            "full_name": self.cleaned_data.get("full_name"),
            "phone_number": self.cleaned_data.get("phone_number"),
            "email": self.cleaned_data.get("email"),
            "city": self.cleaned_data.get("city"),
            "message": self.cleaned_data.get("message"),
        }

        email_subject = "THANKS FOR CONTACTING US"
        email_body = render_to_string(
            "emails/contact-email-body_site-visitor.txt", context
        )

        send_site_visitor_email(email_subject, email_body, context["email"])

    class Meta:
        model = Contact
        fields = "__all__"


class NewsletterForm(forms.ModelForm):
    def send_email_to_admins(self):
        context = {
            "full_name": self.cleaned_data.get("full_name"),
            "email": self.cleaned_data.get("email"),
        }

        email_subject = "SIGNUP FOR NEWSLETTER"
        email_body = render_to_string(
            "emails/newsletter-email-body_admins.txt", context
        )

        send_admin_email(email_subject, email_body)

    def send_email_to_site_visitor(self):
        context = {
            "full_name": self.cleaned_data.get("full_name"),
            "email": self.cleaned_data.get("email"),
        }

        email_subject = "THANKS FOR SIGNING UP FOR OUR NEWSLETTER"
        email_body = render_to_string(
            "emails/newsletter-email-body_site-visitor.txt", context
        )

        send_site_visitor_email(email_subject, email_body, context["email"])

    class Meta:
        model = Newsletter
        fields = "__all__"


class InquiryForm(forms.ModelForm):
    class Meta:
        model = Inquiry
        fields = "__all__"


class ScheduleMeetingForm(forms.ModelForm):
    class Meta:
        model = ScheduleMeeting
        fields = "__all__"

contact/views.py
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, ModelFormMixin, View, BaseFormView
from django.views.generic import RedirectView
from django.urls import reverse_lazy

from .forms import ContactForm, NewsletterForm, InquiryForm, ScheduleMeetingForm


# TODO these handle form views do not handle invalid forms
# TODO there is an assumption that the submitted form is valid. 
# TODO find a way to handle the invalid forms and send the errors back to the templates

class HandleContactFormView(FormView):
    """This view handles the form and if it's valid, redirects it to the success page"""

    form_class = ContactForm
    success_url = reverse_lazy("contact:contact-success")

    def form_valid(self, form):
        form.save()
        form.send_email_to_admins()
        form.send_email_to_site_visitor()
        return super().form_valid(form)


class ContactFormSuccessView(TemplateView):
    template_name = "contact/contact-success.html"


class HandleNewsletterSignupFormView(FormView):
    form_class = NewsletterForm
    success_url = reverse_lazy("contact:newsletter-success")

    def form_valid(self, form):
        form.save()
        form.send_email_to_admins()
        form.send_email_to_site_visitor()
        return super().form_valid(form)


class NewsletterSignupFormSuccessView(TemplateView):
    template_name = "contact/newsletter-success.html"


class HandleInquiryFormView(FormView):
    form_class = InquiryForm
    success_url = reverse_lazy("contact:inquiry-success")

    def form_valid(self, form):
        form.save()
        # TODO Send an email to the person
        return super().form_valid(form)


class InquiryFormSuccessView(TemplateView):
    template_name = "contact/inquiry-success.html"


class HandleScheduleMeetingFormView(FormView):
    form_class = ScheduleMeetingForm
    success_url = reverse_lazy("contact:schedule-meeting-success")
    
    def form_valid(self, form):
        form.save()
        # TODO send an email tot the person
        return super().form_valid(form)
    

class ScheduleMeetingSuccessView(TemplateView):
    template_name = "contact/schedule-meeting-success.html"

templates/contact/ask-question-form.html
{% load static %}
<!-- TODO fix the part of the form that hides on smaller screens -->
<div
  class="bg-black-eerie bg-opacity-90 min-h-screen md:h-screen w-full flex justify-around overflow-y-auto"
>
  <div
    class="lg:w-3/5 xl:w-1/2 md:rounded-lg bg-white pb-10 md:self-center min-h-screen md:min-h-min md:mx-2"
  >
    <div
      class="flex justify-between mb-2 border-b-2 border-b-slate-200 py-1 md:py-3 md:px-5"
    >
      <p class="text-lg self-center pl-4 md:pl-0 font-bold">Inquiry Form</p>
      <i
        id="question-form-close-btn"
        class="fas fa-times-circle text-red-600 p-1 cursor-pointer text-2xl md:text-4xl"
      ></i>
    </div>

    <div class="px-5">
      <div class="">
        <h1 class="text-slate-900 my-1 text-xl text-center font-bold">
          Make any inquiry regarding this apartment.
        </h1>

        <p class="my-2 text-sm sm:text-base text-slate-700">
          The agent in charge of this apartment will reach out to you and answer
          all of your inquiries
        </p>
      </div>

      <form action="{% url 'contact:handle-inquiry' %}" method="POST">
        {% csrf_token %}
        <input
          type="hidden"
          name="{{ ask_question_form.apartment_link.name }}"
          id="{{ ask_question_form.apartment_link.id_for_label }}"
          class="ask-question-apartment-link"
          value=""
        />
        <input
          type="hidden"
          name="{{ ask_question_form.apartment_title.name }}"
          id="{{ ask_question_form.apartment_title.id_for_label }}"
          value="{{ apartment.title }}"
        />
        <input
          type="hidden"
          name="{{ ask_question_form.agent_name.name }}"
          id="{{ ask_question_form.agent_name.id_for_label }}"
          value="{{ apartment.agent.full_name }}"
        />

        <div class="">
          <label
            class="form-label-2"
            for="{{ ask_question_form.full_name.id_for_label }}"
            >Full Name</label
          >
          <input
            class="form-input-2"
            type="text"
            name="{{ ask_question_form.full_name.name }}"
            id="{{ ask_question_form.full_name.id_for_label }}"
            required
          />
        </div>

        <div class="mt-4">
          <label
            class="form-label-2"
            for="{{ ask_question_form.email.id_for_label }}"
            >Your Email Address</label
          >
          <input
            class="form-input-2"
            type="email"
            name="{{ ask_question_form.email.name }}"
            id="{{ ask_question_form.email.id_for_label }}"
          />
        </div>

        <div class="mt-4">
          <label class="form-label-2" for="{{ ask_question_form.phone_number.id_for_label }}"
            >Your Phone Number</label
          >
          <input
            class="form-input-2"
            type="text"
            name="{{ ask_question_form.phone_number.name }}"
            id="{{ ask_question_form.phone_number.id_for_label }}"
            placeholder="e.g: +233549223589"
            required
          />
        </div>

        <div class="mt-4">
          <label for="{{ ask_question_form.question.id_for_label }}" class="form-label-2">Your Question</label>
          <textarea
            name="question"
            id="{{ ask_question_form.question.id_for_label }}"
            cols="30"
            rows="4"
            class="form-input-2"
            required
          ></textarea>
        </div>

        <div class="mt-5">
          <button class="blue-btn-rounded font-bold">Submit Question</button>
        </div>
      </form>
    </div>
  </div>
</div>

templates/contact/contact-success.html
{% extends 'base.html' %}

{% block title %}Information Sent Successfully{% endblock title %}


{% block content %}

<div class="my-20 flex justify-around">
  <div class="bg-slate-800 mx-5 self-center lg:w-4/5 xl:3/5 py-12 px-10">
    <h2 class="text-2xl md:text-4xl text-white py-4 font-semibold text-center">Thank you, your message has been delivered successfully</h2>
    <p class="text-base md:text-lg text-slate-200 py-3">Our Team will process your request in the shortest time possible and contact you with a response.</p>

    <div class="">
      <a class="contact-success-link" href="{% url 'pages:homepage' %}">
        <i class=" self-center fa-solid fa-backward"></i><span>go back home</span>
      </a>
      <a class="contact-success-link mt-3" href="{% url 'apartments:list-apartments' %}">
       <span>explore our apartments</span>
      </a>
    </div>
  </div>
</div>

{% endblock content %}

templates/contact/inquiry-success.html
{% extends 'base.html' %}

{% block title %}Inquiry Sent Successfully{% endblock title %}


{% block content %}

<div class="my-20 flex justify-around">
  <div class="bg-slate-900 mx-5 self-center lg:w-4/5 xl:3/5 py-12 px-10">
    <h2 class="text-2xl md:text-4xl text-white py-4 font-semibold text-center">Your Inquiry has been sent successfully.</h2>
    <p class="text-base md:text-lg text-slate-200 py-3">The agent in charge of the property will reach out and answer your questions briefly.</p>

    <div class="">
      <a class="contact-success-link" href="{% url 'pages:homepage' %}">
        <i class=" self-center fa-solid fa-backward"></i><span>go back home</span>
      </a>
      <a class="contact-success-link mt-3" href="{% url 'apartments:list-apartments' %}">
       <span>explore our apartments</span>
      </a>
    </div>
  </div>
</div>


{% endblock content %}

templates/contact/newsletter-success.html
{% extends 'base.html' %}

{% block title %}Newsletter signup success{% endblock title %}


{% block content %}

<div class="my-20 flex justify-around">
  <div class="bg-slate-900 mx-5 self-center lg:w-4/5 xl:3/5 py-12 px-10">
    <h2 class="text-2xl md:text-4xl text-white py-4 font-semibold text-center">Thank you for signing up to our newletter.</h2>
    <p class="text-base md:text-lg text-slate-200 py-3">We will send you periodic emails with our latest apartments.</p>

    <div class="">
      <a class="contact-success-link" href="{% url 'pages:homepage' %}">
        <i class=" self-center fa-solid fa-backward"></i><span>go back home</span>
      </a>
      <a class="contact-success-link mt-3" href="{% url 'apartments:list-apartments' %}">
       <span>explore our apartments</span>
      </a>
    </div>
  </div>
</div>


{% endblock content %}

templates/contact/schedule-meeting-form.html
{% load static %}
<!-- TODO fix the part of the form that hides on smaller screens -->
<div
  class="bg-black-eerie bg-opacity-90 min-h-screen md:h-screen w-full flex justify-around"
>
  <div
    class="lg:w-3/5 xl:w-1/2 bg-white pb-10 md:self-center min-h-screen md:min-h-min md:mx-2 overflow-y-auto"
  >
    <div
      class="flex justify-between mb-2 border-b-2 border-b-slate-200 py-1 md:py-3 md:px-5"
    >
      <p class="text-lg self-center pl-4 md:pl-0 font-bold">
        Meeting Schedule Form
      </p>
      <i
        id="schedule-meeting-form-close-btn"
        class="fas fa-times-circle text-red-600 p-1 cursor-pointer text-2xl md:text-4xl"
      ></i>
    </div>

    <div class="px-5">
      <div class="">
        <h1 class="text-slate-900 my-1 text-xl text-center font-bold">
          Schedule a meeting with the agent.
        </h1>

        <p class="my-2 text-sm sm:text-base text-slate-700">
          The agent in charge of this apartment will reach out to you for all
          further details.
        </p>
      </div>

      <form action="{% url 'contact:schedule-meeting' %}" method="POST">
        {% csrf_token %}
        <input
          type="hidden"
          name="{{ schedule_meeting_form.apartment_link.name }}"
          id="{{ schedule_meeting_form.apartment_link.id_for_label }}"
          class="schedule-meeting-apartment-link"
          value=""
        />
        <input
          type="hidden"
          name="{{ schedule_meeting_form.apartment_title.name }}"
          id="{{ schedule_meeting_form.apartment_title.id_for_label }}"
          value="{{ apartment.title }}"
        />
        <input
          type="hidden"
          name="{{ schedule_meeting_form.agent_name.name }}"
          id="{{ schedule_meeting_form.agent_name.id_for_label }}"
          value="{{ apartment.agent.full_name }}"
        />

        <!-- TODO customize the appearance of the date-time field -->
        <div class="">
          <label for="{{ schedule_meeting_form.meeting_date_and_time.id_for_label }}" class="form-label-2"
            >Date and Time</label
          >
          <input
            type="datetime-local"
            name="{{ schedule_meeting_form.meeting_date_and_time.name }}"
            id="{{ schedule_meeting_form.meeting_date_and_time.id_for_label }}"
            class="form-input-2"
          />
        </div>

        <div class="mt-4">
          <label
            class="form-label-2"
            for="{{ schedule_meeting_form.full_name.id_for_label }}"
            >Full Name</label
          >
          <input
            class="form-input-2"
            type="text"
            name="{{ schedule_meeting_form.full_name.name }}"
            id="{{ schedule_meeting_form.full_name.id_for_label }}"
            required
          />
        </div>

        <div class="mt-4">
          <label
            class="form-label-2"
            for="{{ schedule_meeting_form.email.id_for_label }}"
            >Your Email Address</label
          >
          <input
            class="form-input-2"
            type="email"
            name="{{ schedule_meeting_form.email.name }}"
            id="{{ schedule_meeting_form.email.id_for_label }}"
          />
        </div>

        <div class="mt-4">
          <label
            class="form-label-2"
            for="{{ schedule_meeting_form.phone_number.id_for_label }}"
            >Your Phone Number</label
          >
          <input
            class="form-input-2"
            type="text"
            name="{{ schedule_meeting_form.phone_number.name }}"
            id="{{ schedule_meeting_form.phone_number.id_for_label }}"
            placeholder="e.g: +233549223589"
            required
          />
        </div>
        <div class="mt-5">
          <button class="blue-btn-rounded font-bold">Submit Schedule</button>
        </div>
      </form>
    </div>
  </div>
</div>

templates/contact/schedule-meeting-success.html
{% extends 'base.html' %}

{% block title %}Meeting Scheduling Successful{% endblock title %}


{% block content %}

<div class="my-20 flex justify-around">
  <div class="bg-slate-900 mx-5 self-center lg:w-4/5 xl:3/5 py-12 px-10">
    <h2 class="text-2xl md:text-4xl text-white py-4 font-semibold text-center">Meeting Scheduled Successfully</h2>
    <p class="text-base md:text-lg text-slate-200 py-3">Our agent will reach out to you and process all required information</p>
    <p class="text-base md:text-lg text-slate-400 pt-1 pb-3">Note that you can cancel your meeting at any time by sending us an e-mail</p>

    <div class="">
      <a class="contact-success-link" href="{% url 'pages:homepage' %}">
        <i class=" self-center fa-solid fa-backward"></i><span>go back home</span>
      </a>
      <a class="contact-success-link mt-3" href="{% url 'apartments:list-apartments' %}">
       <span>explore our apartments</span>
      </a>
    </div>
  </div>
</div>


{% endblock content %}