apartments/urls.py
from django.urls import path

from .views import ApartmentDetailView, ApartmentListView

app_name = "apartments"
urlpatterns = [
    path('', ApartmentListView.as_view(), name="list-apartments"),
    path('<slug:slug>/', ApartmentDetailView.as_view(), name="apartment-detail"),
]

contact/urls.py
from django.urls import path
from .views import (
    HandleContactFormView,
    ContactFormSuccessView,
    HandleNewsletterSignupFormView,
    NewsletterSignupFormSuccessView,
    HandleInquiryFormView,
    InquiryFormSuccessView,
    HandleScheduleMeetingFormView,
    ScheduleMeetingSuccessView,
)

app_name = "contact"
urlpatterns = [
    # contact form urls
    path("contact-us/", HandleContactFormView.as_view(), name="handle-contact"),
    path(
        "contact-us/success/", ContactFormSuccessView.as_view(), name="contact-success"
    ),
    # newsletter signup urls
    path(
        "newsletter-signup/",
        HandleNewsletterSignupFormView.as_view(),
        name="handle-newsletter",
    ),
    path(
        "newsletter-signup/success/",
        NewsletterSignupFormSuccessView.as_view(),
        name="newsletter-success",
    ),
    # inquiry
    path("ask-question/", HandleInquiryFormView.as_view(), name="handle-inquiry"),
    path(
        "ask-question/success/",
        InquiryFormSuccessView.as_view(),
        name="inquiry-success",
    ),
    # schedule meeting
    path(
        "schedule-meeting/",
        HandleScheduleMeetingFormView.as_view(),
        name="schedule-meeting",
    ),
    path(
        "schedule-meeting/success/",
        ScheduleMeetingSuccessView.as_view(),
        name="schedule-meeting-success",
    ),
]

pages/urls.py
from django.urls import path

from .views import HomePageView

app_name="pages"
urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
]

urls.py
# -*- coding: utf-8 -*-
import aldryn_addons.urls
from aldryn_django.utils import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = (
    [
        # add your own patterns here
        path("", include("pages.urls", namespace="pages")),
        path("apartments/", include("apartments.urls", namespace="apartments")),
        path("contact/", include("contact.urls", namespace="contact")),
    ]
    + aldryn_addons.urls.patterns()
    + i18n_patterns(
        # add your own i18n patterns here
        *aldryn_addons.urls.i18n_patterns()  # MUST be the last entry!
    )
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    from django.urls import include, path
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
{% load static contact_extras %}
<html lang="en" class="scroll-smooth">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/tailwind/global.css' %}" />
    <link rel="stylesheet" href="{% static 'icons/all.min.css' %}" />
    
    <link rel="stylesheet" href="{% static 'css/aos/aos.css' %}">

    {% block extra_css %}{% endblock extra_css %}

    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body class="bg-white" id="app-body">
    {% comment %} Top Navbar {% endcomment %}
    <nav class="bg-white lg:border-b-0 lg:shadow-lg">
      <!-- The label -->
      <div class="flex justify-between px-5 h-20">
        <div class="self-center">
          <label class="text-xl font-bold"><a href="{% url 'pages:homepage' %}">
              <div class="flex flex-col">
                <span class="text-blue-700">Isotach</span>
                <hr>
                <span class="text-blue-900">Global</span>
              </div>
            </a>
          </label>
        </div>

        <div class="flex md:space-x-5">
          <!-- The menu items -->
          <div id="mobile-menu-items" class="hidden md:flex md:space-x-5 self-center text-lg overflow-y-auto mb-5 md:mb-0">
            <div class="md:hidden h-20 flex border-b border-b-gray-300">
              <a href="{% url 'pages:homepage' %}" class="self-center text-2xl font-bold">IsotachGlobal</a>
            </div>

            <a href="{% url 'apartments:list-apartments' %}">
              <div class="nav-link-item">
                <div class="mobile-menu-icon-box">
                  <i class="menu-icon fa-solid fa-home"></i>
                </div>
                <span class="nav-link-label">apartments</span>
              </div>
            </a>

            <a href="#advertize">
              <div class="nav-link-item">
                <div class="mobile-menu-icon-box">
                  <i class="menu-icon fa-solid fa-money-bill"></i>
                </div>
                <span class="nav-link-label">advertise</span>
              </div>
            </a>

            <a href="{% url 'pages:homepage' %}#about-us">
              <div class="nav-link-item">
                <div class="mobile-menu-icon-box">
                  <i class="menu-icon fa-solid fa-phone"></i>
                </div>
                <span class="nav-link-label">about Us</span>
              </div>
            </a>

            <a href="{% url 'pages:homepage' %}#services">
              <div class="nav-link-item">
                <div class="mobile-menu-icon-box">
                  <i class="menu-icon fa-solid fa-phone"></i>
                </div>
                <span class="nav-link-label">our services</span>
              </div>
            </a>

            <a href="{% url 'pages:homepage' %}#contact-us">
              <div class="nav-link-item">
                <div class="mobile-menu-icon-box">
                  <i class="menu-icon fa-solid fa-phone"></i>
                </div>
                <span class="nav-link-label">contact Us</span>
              </div>
            </a>

            <a href="{% url 'pages:homepage' %}#faq">
              <div class="nav-link-item">
                <div class="mobile-menu-icon-box">
                  <i class="menu-icon fa-solid fa-question"></i>
                </div>
                <span class="nav-link-label">FAQ</span>
              </div>
            </a>

            <div id="tablet-menu-items"
              class="flex flex-col md:hidden lg:flex lg:flex-row lg:space-x-5 space-y-5 lg:space-y-0">

              <a href="{% url 'pages:homepage' %}#agents">
                <div class="nav-link-item">
                  <div class="mobile-menu-icon-box">
                    <i class="menu-icon fa-solid  fa-people-arrows"></i>
                  </div>
                  <span class="nav-link-label-1">agents</span>
                </div>
              </a>

              <a href="#become-an-agent">
                <div class="nav-link-item">
                  <div class="mobile-menu-icon-box">
                    <i class="menu-icon fa-solid  fa-user-tie"></i>
                  </div>
                  <span class="nav-link-label-1">become an agent</span>
                </div>
              </a>

            </div>

            <!-- Tablet menu icon -->
            <div class="lg:hidden hidden md:flex self-center md:text-2xl cursor-pointer">
              <i id="tablet-menu-icon" class="fa-solid fa-bars"></i>
            </div>
          </div>

          <!-- The mobile menu icon -->
          <div class="md:hidden self-center text-2xl cursor-pointer">
            <i id="mobile-menu-icon" class="fa-solid fa-bars"></i>
          </div>
        </div>
      </div>
    </nav>

    <main>{% block content %}{% endblock content %}</main>

    <!-- Footer -->
    <footer class="bg-slate-900 text-slate-100">
      <div class="flex flex-col-reverse lg:flex-row px-5 lg:px-5 py-10">

        <div class="flex flex-col md:flex-row lg:w-3/5 md:px-2 text-center lg:text-left">
          <div class="md:w-1/3 mt-10 lg:mt-0">
            <h2 class="footer-heading">Address</h2>
            <div class="flex flex-col space-y-5 md:text-left md:px-4">
              <address>
                <p>
                  <i class="fa-solid fa-map-marker-alt"></i> Kotei Rd, Kumasi,
                </p>
                <p>Ghana, West Africa</p>
              </address>
              <a href="tel:+23355155155"><i class="fa-solid fa-phone"></i> +23355155155</a>
              <a href="mailto:info@isotachglobal.com"><i class="fa-solid fa-message"></i> info@isotachglobal.com</a>
            </div>
          </div>

          <div class="md:w-1/3 mt-10 lg:mt-0">
            <h2 class="footer-heading">Useful Links</h2>
            <div class="flex flex-col space-y-5 lg:space-y-5 md:text-left md:px-4">
              <a href="{% url 'apartments:list-apartments' %}">Apartments</a>
              <a href="{% url 'pages:homepage' %}#about-us">About Us</a>
              <a href="{% url 'pages:homepage' %}#services">Our Services</a>
              <a href="{% url 'pages:homepage' %}#contact-us">Contact Us</a>
              <a href="{% url 'pages:homepage' %}#agents">Agents</a>
              <a href="{% url 'pages:homepage' %}#faq">FAQ</a>
            </div>
          </div>

          <div class="md:w-1/3 mt-10 lg:mt-0">
            <h2 class="footer-heading">Socials</h2>
            <div class="flex flex-col space-y-5 text-lg md:text-left md:px-4">
              <a href="#facebook"><i class="fa-brands fa-facebook text-sky-700"></i> Facebook</a>
              <a href="#twitter"><i class="fa-brands fa-twitter text-sky-700"></i> Twitter</a>
              <a href="#linkedin"><i class="fa-brands fa-linkedin text-sky-700"></i> LinkedIn</a>
            </div>
          </div>
        </div>

        <div class="lg:w-2/5 md:w-full">
          {% newsletter_form as newsletter_form %}
          <h2 class="footer-heading">Join Our Newsletter</h2>
          <p class="text-white text-sm py-1">
            Get notified whenever we upload new apartments
          </p>
          <form action="{% url 'contact:handle-newsletter' %}" method="POST">
            {% csrf_token %}
            <div class="mt-2 space-y-1">
              <label for="{{ newsletter_form.full_name.id_for_label }}" class="newsletter-form-label">Your Full Name</label>
              <input 
                class="contact-form-input-1" 
                type="text" 
                name="{{ newsletter_form.full_name.name }}"
                id="{{ newsletter_form.full_name.id_for_label }}" 
                {% if newsletter_form.full_name.field.required %}required{% endif %}
              />
            </div>
            <div class="mt-4 space-y-1">
              <label for="{{ newsletter_form.full_name.id_for_label }}" class="newsletter-form-label">Your Email Address</label>
              <input 
                class="contact-form-input-1" 
                type="email" 
                name="{{ newsletter_form.email.name }}"
                id="{{ newsletter_form.email.id_for_label }}" 
                {% if newsletter_form.email.field.required %}required{% endif %}
              />
            </div>
            <div class="mt-4">
              <button type="submit" class="blue-btn-rounded">
                Register
              </button>
            </div>
          </form>
        </div>
      </div>

      <div class="text-sm flex justify-around bg-black-rich text-white">
        <div class="py-2 md:flex space-x-5 space-y-1 md:space-y-0">
          <!-- TODO change the 2022 and use a scipt to insert the year -->
          <i class="fa-solid fa-copyright mr-1"></i> copyright, 2022 - Isotach Global
          <p class="text-center text-gray-300">All Rights Reserved</p>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/aos/aos.js' %}"></script>
    <script>
      AOS.init()

      // HANDLE MOBILE MENU -----------------------------------------------------------------------
      const document_body = document.querySelector("#app-body");

      const mobile_menu_icon = document.getElementById("mobile-menu-icon");
      const mobile_menu_items = document.getElementById("mobile-menu-items");

      function showMobileMenuItems(e) {
        // Change the mobile menu icon to a times or bars
        mobile_menu_icon.classList.toggle("fa-bars");
        mobile_menu_icon.classList.toggle("fa-times");
        mobile_menu_icon.classList.toggle("text-3xl");
        mobile_menu_icon.classList.toggle("text-red-600");

        // Handle the hiding and showing of the menu items
        mobile_menu_items.classList.toggle("hidden");
        mobile_menu_items.classList.toggle("mobile-menu");

        document_body.classList.toggle('overflow-hidden')
      }

      const window_width = window.innerWidth;
      function handleResizeMobile(e) {

        if (window_width > 767) {
          mobile_menu_items.classList.add("hidden");
          mobile_menu_items.classList.remove("mobile-menu");
        }
      }

      mobile_menu_icon.addEventListener("click", showMobileMenuItems);
      window.addEventListener("resize", handleResizeMobile);

      // HANDLE TABLET MENU ----------------------------------------------------------------
      const tablet_menu_icon = document.getElementById("tablet-menu-icon");
      const tablet_menu_items = document.getElementById("tablet-menu-items");

      function showTabletMenuItems(e) {
        tablet_menu_icon.classList.toggle("fa-bars");
        tablet_menu_icon.classList.toggle("fa-times");
        tablet_menu_icon.classList.toggle("text-3xl");
        tablet_menu_icon.classList.toggle("text-red-600");

        // Hide or show the mobile menu items
        tablet_menu_items.classList.toggle("md:hidden");
        tablet_menu_items.classList.toggle("tablet-menu");
      }

      function handleResizeTablet(e) {

        if (window_width <= 767 || window_width >= 1024) {
          tablet_menu_items.classList.add("md:hidden");
          tablet_menu_items.classList.remove("tablet-menu");
        }
      }

      // Close the menu when nav link items are clicked
      const nav_link_items = document.getElementsByClassName("nav-link-item");
      if (window_width <= 767) {
        for (link of nav_link_items) {
          link.addEventListener("click", showMobileMenuItems)
        }
      }

      tablet_menu_icon.addEventListener("click", showTabletMenuItems);
      window.addEventListener("resize", handleResizeTablet);
    </script>

    {% block javascript %}{% endblock javascript %}

  </body>

</html>